<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "oidc_server"
 *
 * Auto generated by Extension Builder 2021-02-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'OIDC Server',
    'description' => 'OpenID Connect server for TYPO3.',
    'category' => 'services',
    'author' => '',
    'author_email' => '',
    'state' => 'beta',
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-13.1.99',
            'oauth2_server' => '2.0.0-2.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
