services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      OpenIDConnectServer\Repositories\IdentityProviderInterface: '@R3H6\OidcServer\Domain\Repository\UserRepository'

  R3H6\OidcServer\:
    resource: '../Classes/*'

  R3H6\OidcServer\Controller\:
    resource: '../Classes/Controller/*'
    public: true

  OpenIDConnectServer\ClaimExtractor:
    class: 'OpenIDConnectServer\ClaimExtractor'
    factory: '@R3H6\OidcServer\Domain\Factory\ClaimExtractorFactory'

  OpenIDConnectServer\IdTokenResponse:
    public: true
    arguments:
      $identityProvider: '@R3H6\OidcServer\Domain\Repository\UserRepository'
      $claimExtractor: '@OpenIDConnectServer\ClaimExtractor'

  R3H6\OidcServer\EventListener\SetIdTokenResponseOnAuthorizationServer:
    tags:
      - name: event.listener

  R3H6\OidcServer\EventListener\HandlePromptParamForConsent:
    tags:
      - name: event.listener

  R3H6\OidcServer\EventListener\HandlePromptParamForAuthentication:
    tags:
      - name: event.listener

  R3H6\OidcServer\EventListener\AddRoutesForAuthorizationServer:
    tags:
      - name: event.listener

