base: 'https://typo3-oidc-server.ddev.site/'
dependencies:
  - oauth2-server/identity-provider
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: ''
imports:
  -
    resource: 'EXT:oidc_server/Configuration/Site/Config.yaml'
